# Generated by Django 4.2.7 on 2023-11-29 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=10, verbose_name='Device Id')),
                ('co2', models.CharField(max_length=10, verbose_name='CO2')),
                ('nox', models.CharField(max_length=10, verbose_name='NOx')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20, verbose_name='First Name')),
                ('second_name', models.CharField(max_length=20, verbose_name='Second Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('address', models.CharField(max_length=200, verbose_name='Address')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('gas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gas_api.gas')),
            ],
        ),
    ]
