# Generated by Django 4.2.7 on 2023-11-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gas_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gas',
            name='hum',
            field=models.CharField(default=0, max_length=10, verbose_name='Humidity'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gas',
            name='temp',
            field=models.CharField(default=0, max_length=10, verbose_name='Temperature'),
            preserve_default=False,
        ),
    ]
